#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /etc/keepalived/scripts/sync_leases.sh daemon_push
    procd_set_param respawn
    procd_set_param stdout 0
    procd_set_param stderr 0
    procd_close_instance
}

stop_service() {
    rm -f /tmp/leases_sync_status
}
